let concecionario = require("./concecionario");
let auto =require("./autos");
let personas=require("./personas");
//console.log(concecionario.buscarAuto("JJK116"));
//concecionario.venderAuto("JJK116");
//console.log(concecionario.buscarAuto("JJK116"));
//console.log(concecionario.autosParaLaVenta());
//console.log(concecionario.autosNuevos());
//console.log(concecionario.listaDeVentas(concecionario.autos));
//console.log(concecionario.totalDeVentas());
//console.log(concecionario.puedeComprar(auto[1],personas[0]));
//console.log(concecionario.autosQuePuedeComprar(personas[0]));
